NeedleAgent:
  llm:
    model: gpt-4o-mini
  indexer:
    type: faiss     # faiss, graph
    faiss_directory: backend/data/faiss_index
    graph_nodes:
      - policies
      - medical_reports
      - client_emails
