"NeedleAgent":
  "llm":
    "model": "gpt-4o-mini"
  "indexer":
    "faiss_directory": "backend/vectordb_indexes/faiss_indexer_insurance"
"Dataset":
  "ground_truth_dataset_path": "backend/data/evaluation_datasets/needle_agent/client3_report3_MenoraPolicy.jsonl"
"Evaluator":
  "metrics": ["Faithfulness","LLMContextRecall","LLMContextPrecisionWithReference"]
  "evaluator_llm": "gpt-4o-mini"
  "output_path": "backend/data/evaluation_datasets/needle_agent/client3_report_MenoraPolicy_evaluation_results.json"